### ISSUE TITLE
Confirmation for exiting a room you are playing in

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#124]
Its too easy to leave and then the other play thinks you were done playing.

**Comment by Davidvieweg** [comment]
I think I fulfilled the requirements. ( see pr panel-attack/panel-attack#550 )

**Comment by Endaris** [comment]
Alternative suggestion to creating a menu:  
Block the first B/Up input in the first ~0.3s (human reaction time) after returning to character select.  
Typically this happens by courtesy of  B->A, B->B, Up -> A or Up -> B
Since a quick A input may be intentional to instantly ready up again, Up and B are part of every single quick quit so blocking them briefly should prevent the vast majority of accidental quits without adding a potentially annoying menu. (My train of thoughts: Either you can B mash through that as well or it's going to be one of those Zelda Owl moments where you get sent back to character select all the time when you actually want to quit)

This idea also removes the requirement to add localization.

**Comment by JamesVanBoxtel** [comment]
I think the latter idea is worth doing. If its not sufficient we can extend it more or go to the other way.

**Comment by Endaris** [comment]
On sceneRefactor this is "solved" by disabling navigation to the leave button using arrow keys completely, only inputting "swap2, swap2" or "swap2, swap1" (or using touch inputs) can make you quit the room.
This can still easily be adjusted to only work as a temporary block rather than a permanent.
