### ISSUE TITLE
Option for garbage blocks based on player position

### ISSUE THREAD

**Issue by MizunoKetsuban** [panel-attack/panel-game#141]
For the Tetris Attack and PLDS type skins. Somewhat similar to the portrait2 system.

In 1p VS and 1p Training, the garbage block would use the P2 variant (so red, in terms of TA visuals)

**Comment by Endaris** [comment]
Not as easy to add like this for 1p vs self because it makes the game send from player 1 to player 1, meaning a generic setting to have player 1 use one color and player 2 use the other is not going to cut it.
I can imagine this happening for 2p vs and training but doing this for 1p modes might require injections of graphics related code into parts of the engine where we really don't appreciate to have them.

Related discussion: https://discord.com/channels/196674532491132937/854285957347147778/987482247185707008

**Comment by MizunoKetsuban** [comment]
I can understand not changing the color of the block in the 1p modes. It's the least important part of that to me anyway, I simply suggested it to see if it was possible. The other part is ultimately more important anyway.

**Comment by Endaris** [comment]
Relatively high complexity for a highly optional feature that is not actively being missed by the community. This issue is the only mention of it as far as I'm aware.
Additionally there are future questions that aren't answered yet, e.g. what happens in scenarios with more than 2 players.
Overall I don't think the increase in complexity is worth the very niche uses so I'm closing this.
