### ISSUE TITLE
Ability to fix win counts manually

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#227]
When the game crashes or lobby is closed, the win count can be off, this makes it so streams of tournaments don't show the right win count and we have to maintain a separate overlay.

We should allow the spectator to press some sort of key combo to be able to adjust the win count. This would only affect local replay records and what was visually on screen, not interact with the server.

We need to prevent going negative and any other crash cases.

**Comment by Endaris** [comment]
Imo the issue goes beyond just tournament matches, even for regular sets it would be most welcome if win counts could be kept inbetween crashes.
While this would require server protocol changes (e.g. tracking whether the room was closed voluntarily or due to an error and keeping it "open" for a brief period while hiding it from other players and awaiting people to rejoin), I feel like overall this would be more sustainable and preferable over potential abuse or the necessity to regularly release a "tournament client" while also avoiding all issues resulting from allowing client-side manipulation of values that technically shouldn't be manipulated like the mentioned crashes when going negative.

**Comment by JamesVanBoxtel** [comment]
The problem is its kinda hard to know the win count for sure, do you always assume a lag disconnect or crash doesn't count as a win? Making a bunch of server changes like that will definitely be harder and more risky.

BTW this can't really be abused because its only the local view of the match, no one else sees the modified numbers.

**Comment by AegisCrusader** [comment]
Client-side is the way to go with this, IMO.
