### ISSUE TITLE
add support for menu translation packs

### ISSUE THREAD

**Issue by jon12156** [panel-attack/panel-game#24]
We would very much like the game available in at least:
(English)
Japanese - They have a very large player base I'd like to capture.
Portuguese - we have a lot of members from Brazil

**Comment by April93** [comment]
Worth noting that there's a question of whether it should be done via graphics (part of menu art that's customizable) or done via strings (text overlayed onto menu art?). The latter would be easier to localize with customizable art being language-agnostic. But the former allows alternative menu item styles like icons.

**Comment by JamesVanBoxtel** [comment]
This is kind of supported via the localization file, however we don't have a way to localize the images outside the theme.

**Comment by JamesVanBoxtel** [comment]
In the future it would be nice to be able to provide alternate image assets and also have one folder per language instead of them all being in one file

**Comment by Endaris** [comment]
Based on what I investigated on the change history of the localization, at the time the issue was created there was in fact no localization for the 2 languages mentioned in the description. They were added to the game later that year with panel-attack/panel-attack#128 so I would strongly assume that the original intent of the issue has been fulfilled.

@JamesVanBoxtel If you want to keep this idea of localized image assets around, I suggest you create a new issue.
