### ISSUE TITLE
Remember log messages

### ISSUE THREAD

**Issue by AegisCrusader** [panel-attack/panel-game#317]
We could try and put log messages into a queue, and store a certain amount of log messages, such as the previous 30 message that are debug and above. When someone crashes, we send those 30 log messages to the server too along with the other information so we can get more context.

**Comment by Endaris** [comment]
Major issue being that we'd have to add said log messages because except for startup and telegraph, the amount of logging we do is near nil and more likely than not useless in the overwhelming majority of bugs that we can't already analyze based on the crash message / stack trace alone.
It seems more promising to simply add our own "crash handling" code for errors we cannot pinpoint as the outcome for the user will be the same, whether be it through logging or a crash - just that a controlled crash shortens the way of communication because we can display the info directly in the error message rather than having to go out of our way and fetch it from the server.

**Comment by Endaris** [comment]
Closing this issue because of following actions having been taken:
- on crash, the client now writes a `crash.log` file to the save directory
- the error message explicitly asks players to share the crash.log with developers
- on quit without a crash, the client now writes a debug.log to the save directory (for problems that don't end in a crash)

I think the premise of "going to the server and checking logs if anyone had any obscure bugs but didn't report them" is not workable for a variety of reasons:
- only sending a partial log to the server may leave the actual cause of the crash obscure (particularly for network-related and framecrossing errors)
- server storage is a little precious
- we still don't really log enough to get any worthwhile information or only in debug setting
