### ISSUE TITLE
Improve replay playback usability

### ISSUE THREAD

**Issue by Endaris** [panel-attack/panel-game#333]
Ideas:
Add a visual indicator that tells you the current playback speed.
Don't increase replay speed linearly but instead exponentially (x0.5, x1, x2, x4, x8, x16, maybe with x3 included as well).

**Comment by z26** [comment]
I did this (except the 0.5x part for now) while I was working on [issue 822](https://github.com/panel-attack/panel-game/issues/303)
I haven't implemented half speed yet because I'm still undecided between making the playback code support any float values, or only hardcoding 0.5x to work.


Some thoughts about usability:

- I currently feel that without the x0 speed it feels better to use, but my commits included it anyway.
- moving frame by frame feels really slow, I wonder if the frame advance could scale with the playback speed? but then people are going to want a faster negative speed for that purpose, but adding too many speeds is iffy especially when you can only rewind 5s.
- I'm considering that maybe entering pause should actually reset the playback speed to 1x (makes your current speed when exiting pause more predictable, and also lets you easily reset the speed whenever you want) but I could also see this idea being annoying in some situations.
- Alternatively, the raise button could either reset speed back to 1x, or slow playback down to half the current speed.
- I feel that while 0.5x would be a valuable feature, it would also be an extra step between 1x and -1x that might make the user experience worse.
- Would be nice to make the rollback buffer larger to rewind 10s, like we discussed on discord.

**Comment by JamesVanBoxtel** [comment]
I have a branch lying around that allows any arbitrary speed of playback and inputs. Maybe we could use that for half speed, but I think the PR as it is now is good enough. Fixes a lot of the main sticking points. Lets live with it and file any new issues if we feel they are important.

**Comment by JamesVanBoxtel** [comment]
Fixed by https://github.com/panel-attack/panel-attack/pull/954
