### ISSUE TITLE
Client disconnects from server if joining a game that's been in progress for too long.

### ISSUE THREAD

**Issue by jon12156** [panel-attack/panel-game#41]
could perhaps be solved by having a separate thread (coroutine) to fast forward the replay the client gets upon joining the game, 

or, this could be solved by sending the state of the game at a certain frame instead of the replay of the game so far.
games states don't exist yet.  the server doesn't know any game logic, so the game state would need to be retrieved from a player or other spectator. 
This would be a good step towards being able to have better playback of replays too. (rewind, a proper playback bar at the bottom, etc)

**Comment by Omio** [comment]
I wonder if a keyframe system at every 6,000 frames would work, where when catching up, the most recent keyframe is sent from whoever, and the the replay from that keyframe after, meaning that you're catching up to about 100 seconds.

I only worry that creating too many keyframes might impact performance, but too few keyframes makes watching long replays down the road moot.

EDIT TO ADD:
This might also be a good time to add the "telegraph" as well, since that'd be part of the game state.

**Comment by Raspberryfloof** [comment]
I think the reason this happens is because when initially connecting to a game in progress, the client does fast-forwarding outside of a variable_step() call and disabled all rendering/sound processing/other processing until it completes this initial fast-forward.  This lets it go as fast as it possibly can while fast-forwarding, but it also means that it either doesn't respond to additional server messages or drops them and ends up too far out of sync.

I remember playing around with a change a while ago that did fast-forwarding in a variable_step() call and changed the fast-forward function to just go a fixed but very large number of loops forward any time you lagged too far behind, but it constantly ran into the "Room initialization failed" problem if the game ended while the client was still fast-forwarding, so I dropped it.

**Comment by JamesVanBoxtel** [comment]
The processing of messages out of order is also what can cause
https://github.com/panel-attack/panel-game/issues/52

I wonder if we make sure it holds onto all new message in order and simulates them if that will fix this problem too.

**Comment by JamesVanBoxtel** [comment]
I think this is fixed in the latest beta. We should monitor and close this once it goes in the main build and we don't see any more issues.
