### ISSUE TITLE
SceneRefactor: sometimes catching up to a game doesn't work, frame bar starts counting down.

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#411]
https://github.com/panel-attack/panel-game/assets/8935453/6c45b8dc-0ee3-4f24-b1ba-a97c3fdb6972

**Comment by Endaris** [comment]
Can you fetch the replay for that?
In my experience this is caused by incorrectly interpreting a board state as match end rather than just failing to toggle `play_to_end` on the stack.
When going frame by frame, it stops at 5100 out of 5150 and then only unprocessed frames count up (meaning the game is still going on but somehow `match.run` decided the game is over).

**Comment by JamesVanBoxtel** [comment]
Yeah this doesn't happen anymore, it was caused by the server mixing up 1 and 2s inputs in the replay, fixed now
