### ISSUE TITLE
Blank screen on startup

### ISSUE THREAD

**Issue by ShimmerFairy** [panel-attack/panel-game#42]
In linux, typing `love ./` like the readme says just result is a dark gray window. Console shows output about characters and such, but that's all that happens. No obvious error messages or anything.

Using love 11.3, lua 5.1.5

**Comment by JamesVanBoxtel** [comment]
Does this still happen?

**Comment by Endaris** [comment]
I think this should be closed since the instructions used here for running PA are outdated.
Using the instructions on panelattack.com I have no problem starting PA on a recent Ubuntu desktop so there should be no problem left here.

Even then, I'm able to start the game either via `love ./` in a cloned repo folder too.
